### ISSUE TITLE
Lethal Level Loader update breaks Maritopia's Moon Listing and Cost

### ISSUE THREAD

**Issue by Sourceshard** [Toliann/Maritopia#1]
Lethal Level Loader intercepts moons loaded with LethalExpansion and LethalExpansionCore and displays them on the in-game moon Catalogue.

As such Maritopia does not display or load properly. I believe it is possibly suffering from issues #2 and 3.
I am unaware of whether you can fix this on your end to make it compatible but I wanted to bring it to your attention.

LLL Known Issues (As of 1.1.0.4)

-Mods that skip the initial LAN or Online scene will cause LLL to break by skipping it’s code

-LethalExpansion moons will be 0 route price due to issues with LethalExpansion breaking when SelectableLevel.levelID’s are modified 

-Lethal Expansion moons with uncommon characters in their planet name will likely break the game as LethalExpansion does not sanitise names when setting SelectableLevel asset names and LLL does not validate these names when parsing the automatic configuration system

-Saving and loading a save where a Custom Moon was the last active level will break the game due to an oversight regarding the levelID saved to the save file via ES3

-Issues regarding routing to moons with similar names and/or spaces in the name are known

<img width="1280" alt="image" src="https://github.com/Toliann/Maritopia/assets/37197624/7ed70d52-5319-4ebb-9151-8a32d24c00d5">

**Comment by Toliann** [comment]
Please insert into the LethalLevelLoader.cfg file what I sent you in LethalLevelLoader.cfg, and it should work for you
[LethalLevelLoader.txt](https://github.com/Toliann/Maritopia/files/14230458/LethalLevelLoader.txt)

**Comment by Toliann** [comment]
This should also work for the Celestria map

**Comment by Sourceshard** [comment]
Awesome this override will work. 

Because I am curious. Is this error fixable on your side, Lethal Expansion's side, or LLL's side?

**Comment by Toliann** [comment]
I assume the entire problem lies with LLL
