### ISSUE TITLE
Using a jetpack to fly into the water, underneath it's surface will let you walk around on the floor outside of the water volume.

### ISSUE THREAD

**Issue by Mr-Foxtrot** [Toliann/Maritopia#5]
There seems to be a pocket of air of some sort underneath the water at the bottom of the map just outside where the ship lands. Use a jetpack, fly down there quickly enough so the water doesn't cause you to drown, and boom: you can walk around freely.

Hope this can be fixed.

**Comment by Toliann** [comment]
fixed it in the latest update
